CREATE TABLE `purchaseLinks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`wineId` int NOT NULL,
	`storeName` varchar(255) NOT NULL,
	`url` text NOT NULL,
	`price` decimal(10,2),
	`observation` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `purchaseLinks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `wines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`producer` varchar(255) NOT NULL,
	`vintage` int,
	`country` varchar(100) NOT NULL,
	`region` varchar(255),
	`grapes` varchar(500),
	`style` enum('tinto','branco','rose','espumante') NOT NULL,
	`imageUrl` text,
	`referencePrice` decimal(10,2),
	`subcriteria` json,
	`appearanceScore` int NOT NULL DEFAULT 0,
	`aromasScore` int NOT NULL DEFAULT 0,
	`palateScore` int NOT NULL DEFAULT 0,
	`harmonyScore` int NOT NULL DEFAULT 0,
	`potentialScore` int NOT NULL DEFAULT 0,
	`finalScore` int NOT NULL DEFAULT 0,
	`costBenefit` int NOT NULL DEFAULT 3,
	`shortComment` text,
	`longComment` text,
	`pairings` json,
	`drinkNow` boolean NOT NULL DEFAULT true,
	`canAge` boolean NOT NULL DEFAULT false,
	`isBestBuy` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `wines_id` PRIMARY KEY(`id`)
);
